FROM emscripten/emsdk:1.39.17

RUN apt-get update && apt-get install -y wget build-essential apt-transport-https scons python3 python3-pip
RUN ln -sf /usr/bin/python3 /usr/bin/python

WORKDIR /app

EXPOSE 8000
